### PR TITLE
Fix humphd/brackets#219 - Allow overflow scrolling when in mobile preview mode

### PR DESCRIPTION
**Pull request by AJDBenner**
Fixes https://github.com/humphd/brackets/issues/219

### CODE REVIEW

**Comment by AJDBenner** [comment]
The `.css()` method is required here because brackets sets a style rule on the id which overrules any class that we add.

**Comment by humphd** [comment]
So using `!important` with it won't work in a class?  If that's true, `.css()` is OK.  One other question about this.  Testing this locally I'm noticing that it works, but I don't see a scrollbar at all in the preview pane (i.e., it will scroll, but I can't see that it will scroll).  It works in Firefox, so this might be a Chrome-only bug with `overflow: hidden` being inherited deeply.  I don't think it's a blocker to landing this, if you can't figure it out quickly--we'd just want to file a follow-up bug.  See if you can fix it, though.

**Comment by AJDBenner** [comment]
Using `!important` is working so I've updated the PR to `addClass()` instead of `css()`. I haven't been able to reproduce the bug you're seeing that doesn't show the scrollbar. When I tested this patch in chrome the scrollbar is visible. This patch should be good to go after another quick review.

**Comment by humphd** [comment]
r+

**Pull request merged**
