### PR TITLE
changed declaration to be HTML5 compliant

### LINKED ISSUE #50: Make default HTML file HTML5 compliant
There is currently an issue with the default.html page that doesn't make it HTML5 compliant. Changing the declaration to be <!DOCTYPE html> vs <!doctype html> fixes this.

### PR DESCRIPTION
**Pull request by K-LV**
Fixes #50, changed declaration to be <!DOCTYPE html>

### CODE REVIEW

**Comment by humphd** [comment]
r+.  Can you make sure there aren't any other places where we get this wrong?  We seem to have a few places where we define default/new HTML content in files/code.

**Comment by K-LV** [comment]
The only other place I see is in [bramble](https://github.com/humphd/brackets/blob/bramble/src/filesystem/impls/lib/default.html)

**Comment by humphd** [comment]
File a bug on Bramble for this other one, and let's fix there + update the bbld submodule for this fix at the same time.  I'll merge this in the meantime.

**Comment by K-LV** [comment]
Filed a [bug](https://github.com/humphd/brackets/issues/167) in Bramble to remove the default.html file there.

**Pull request merged**
